package com.correai.api.domain.user;

import org.junit.jupiter.api.Test;

import java.lang.reflect.Field;
import java.lang.reflect.Method;

import static org.junit.jupiter.api.Assertions.*;

class UserTest {

    @Test
    void createAnonymous_shouldCreateUser() {
        User user = User.createAnonymous();

        assertNotNull(user);
        // ID is generated by JPA, not by create method
        assertNull(user.getId());
    }

    @Test
    void prePersist_shouldSetCreatedAt() throws Exception {
        User user = User.createAnonymous();

        // Set createdAt to null to simulate not set
        Field createdAtField = User.class.getDeclaredField("createdAt");
        createdAtField.setAccessible(true);
        createdAtField.set(user, null);

        // Call prePersist
        Method prePersistMethod = User.class.getDeclaredMethod("prePersist");
        prePersistMethod.setAccessible(true);
        prePersistMethod.invoke(user);

        // Assert createdAt is set
        assertNotNull(createdAtField.get(user));
    }
}
